# Generated by Django 3.1.4 on 2021-05-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_ticket_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
