# Generated by Django 3.1.4 on 2021-05-16 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
