# Generated by Django 3.1.4 on 2021-05-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20210516_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedto',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='AssignedTo',
        ),
    ]
