# Generated by Django 3.1.4 on 2021-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Draft', max_length=100),
        ),
    ]
